---
# tasks file for egeneralov.peervpn

- name: "check : subnet size"
  fail:
    msg: "Too many hosts ({{item | ipaddr('size') }} for {{item}}"
  when: groups.peervpn|length > item|ipaddr('size') - 2
  with_items: "{% set i=[] %}{%for item in networks%}{%if i.append(item.net) %}{%endif%}{%endfor%}{{ i }}"

- include_tasks: "{{ ansible_system }}.yml"
